######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 1 09:14:12 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cannonfield.h gameboard.h lcdrange.h
SOURCES += cannonfield.cpp driver.cpp gameboard.cpp lcdrange.cpp
