######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 1 09:12:52 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lcdrange.h
SOURCES += driver.cpp lcdrange.cpp
