######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 1 09:13:19 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cannonfield.h lcdrange.h
SOURCES += cannonfield.cpp driver.cpp lcdrange.cpp
