######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 1 09:11:58 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += driver.cpp
